config/routes.rb
Rails.application.routes.draw do
  resources :artists do
    resources :songs
  end

  root 'artists#index'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def create
    @artist = Artist.new
    @song = @artist.songs.create(song_params)
    if @artist.save
      render artist_path
    else
      redirect_to root_path
    end
  end

  def update
    @artist = Artist.find(params[:id])
  end

  def new
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def destroy
    @artist = Artist.find(params[:id])
  end

  protected

  def artist_params
    params.require(:artist).permit(:name, :country)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create(song_params)
    redirect_to artist_path(@artist)
  end

  def update
    @song = Song.find(params[:id])
  end

  def destroy
    @song = Song.find(params[:id])
  end

  protected

  def song_params
    params.require(:song).permit(:title, :album, :cover, :year, :ylink)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for Artist.new do |f| %>

<div class="form-group">
       <%= f.label :name %>
       <%= f.text_field :name, class: "form-control", placeholder: ". . ." %>
    </div>

    <div class="form-group">
       <%= f.label :country %>
       <%= f.text_field :country, class: "form-control", placeholder: ". . ."   %>
    </div>


    <%= f.submit (Artist.new.new_record? ? "Create" : "Update"), class: "form-control btn-primary" %>

<% end %>

app/views/artists/edit.html.erb
<div class = 'song_form'>
<%= form_for @artist do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :country %>
    <%= f.text_field :country %><br>

    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/artists/index.html.erb
<h1>Welcome, here you can find your collection</h1>
<body background="./assets/set.png" class="bg">
<% @artists.each do |artist| %>
    <p><%= link_to artist.name, artist %></p>
<% end %>
<br>
<h3><%= link_to "Add an artist", new_artist_path%></h3>

app/views/artists/new.html.erb
<h1>New Author</h1>

<%= render "form" %>

app/views/artists/show.html.erb
<body>
<p>
  <h1 class='artisttitle'><%= @artist.name %></h1>
  <h2 class='artistcountry'><%= @artist.country %></h2>
</p>

<%= @artist.songs.each do |song| %>
    <div class = 'container'><img src ="<%=song.cover%>"</div>
    <%= song.album %>
    <%= song.year %>
    <%= song.ylink %>
    <% end %>

<h2>Add a song for this artist!</h2>
<div class = 'song_form'>
<%= form_for([@artist, @artist.songs.build]) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br>

    <h4>Upload album cover</h4>
    <%= f.label :cover %>
    <%= f.text_field :cover %><br>
  </p>
  <p>
    <%= f.label :album %>
    <%= f.text_field :album %><br>
  </p>
  <p>
    <%= f.label :year %>
    <%= f.text_field :year %><br>
  </p>
  <p>
    <h4>Add Youtube Link here</h4>
    <%= f.label :ylink %>
    <%= f.text_field :ylink %><br>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

<div class = 'editback'>
<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artist_path %>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Youbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>
</body>
</html>

app/views/songs/index.html.erb
<h2>Songs</h2>
<%= @songs.each do |song| %>
    <%= image_tag('song.cover') %><br>
    <%= song.album %><br>
    <%= song.year %><br>
    <%= song.ylink %><br>
    <br>
<% end %>